### ISSUE TITLE
Overriding Location Entity

### ISSUE THREAD

**Issue by davidroberto** [coopTilleuls/CoopTilleulsSyliusClickNCollectPlugin#11]
Hi,

I believe the Traits ClickNCollectShippingMethod and ClickNCollectShipment should type-hint LocationInterface instead of Location in order to be able to override the Location entity properly?

Example (in Entity/ClickNCollectShippingMethod): 
``
public function addLocation(Location $location): void
``

should be : 

``
public function addLocation(LocationInterface $location): void
``

**Comment by dunglas** [comment]
Good catch indeed! I'll fix this.
