### ISSUE TITLE
Selecting a picking slot is not mandatory

### ISSUE THREAD

**Issue by jacquesbh** [coopTilleuls/CoopTilleulsSyliusClickNCollectPlugin#27]
If the customer selects the Click and Collect shipping method, and does **not** select a slot in the calendar, he can still continue to the next step.

This could lead to a customer coming whenever he wants, which is not what we want!

Possible solutions are:
- Add a JS validation
- Add a PHP validation

I prefer both but if I had to make a choice, the frontend JS validation is better in an UX point of view.

Thank you!

**Comment by snakewa** [comment]
Agree with @jacquesbh

**Comment by toofff** [comment]
Good idea @jacquesbh :+1:

**Comment by thcolin** [comment]
Hi ! Thanks for your time, I added a JS validation on slot selection, tell me if it fix your issue !
