### ISSUE TITLE
Time slot error when selecting another shipping method

### ISSUE THREAD

**Issue by jacquesbh** [coopTilleuls/CoopTilleulsSyliusClickNCollectPlugin#30]
Hi,

When I select a location and a slot, then validate, then come back and use a different shipping method and validate again, I get this error (with correct value):
```
The time slot "{{ value }}" is not available anymore.
```

This is really a blocking issue. The customer cannot even change their mind…

**Comment by thcolin** [comment]
Hello,

I tried to reproduce the issue but I did not succeed, can you confirm that you still have the error on `master` please ?

**Comment by jacquesbh** [comment]
@thcolin I've made a PR for this. I still have the issue on master.
