### ISSUE TITLE
If the Rule contains more than a month old dates, no slots are displayed

### ISSUE THREAD

**Issue by jacquesbh** [coopTilleuls/CoopTilleulsSyliusClickNCollectPlugin#32]
If you use this rule:
```
FREQ=MINUTELY;INTERVAL=20;BYHOUR=9,10,11,12,13,14,15,16;BYDAY=MO,TU,WE,TH,FR;DTSTART=20200328T080000;DTEND=20200328T082000
```

Then the `\Recurr\Rule` object will return the dates from March 28th, limited to 732 occurrences.
This leads, today, to no displayed slots.

This can be fixed by updating the `DTEND` and `DTSTART` via the admin, but it's really not usable.

**Comment by thcolin** [comment]
Thanks, a fix will be added in the next release of the plugin !
