### ISSUE TITLE
Override SlotAvailable Constraint

### ISSUE THREAD

**Issue by davidroberto** [coopTilleuls/CoopTilleulsSyliusClickNCollectPlugin#34]
Hey,

When overriding the SlotAvailable Constraint (in order to override the error message), the SlotAvailableValidator throw an exception because the validate method checks if the constraint is an instance of SlotAvailable.
A better way is to check if it's a SlotAvailableInterface (and implement it in the SlotAvailable constraint), so that the SlotAvailable can be overrided.

Anyway, thanks a lot for this plugin!

**Comment by thcolin** [comment]
Hello !

Does the changes on PR #39 would solve your issue ?
