### ISSUE TITLE
Please, be compatible with last Sylius install

### ISSUE THREAD

**Issue by ChoOo7** [coopTilleuls/CoopTilleulsSyliusClickNCollectPlugin#60]
Doing 
root@chooo7:/var/www/ecomDocker# docker-compose exec php composer require tilleuls/sylius-click-n-collect-plugin

 [InvalidArgumentException]
  Package tilleuls/sylius-click-n-collect-plugin has requirements incompatible with your PHP version, PHP extensions and Composer version:
    - tilleuls/sylius-click-n-collect-plugin v0.2.0 requires php ^7.4 which does not match your installed version 8.0.15.

If your code is compatible with php 8, maybe it's just a package description update ?

Thanks for your work

**Comment by romainallanot** [comment]
closed this as completed in #68
