### ISSUE TITLE
add support for Symfony 6 (for all SF dependencies)

### ISSUE THREAD

**Issue by JulieNobody** [coopTilleuls/CoopTilleulsSyliusClickNCollectPlugin#63]
Could we also add support for Symfony 6, for all SF dependencies (could be done in another PR)?

_Originally posted by @dunglas in https://github.com/coopTilleuls/CoopTilleulsSyliusClickNCollectPlugin/pull/62#discussion_r815982376_

**Comment by romainallanot** [comment]
closed this as completed in #65

**Comment by romainallanot** [comment]
closed this as completed in #65
